name: mybinder-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - ipykernel
  - voila
  - appmode
  - numpy=1.24.3
  - pandas
  - seaborn
  - matplotlib
  - ipywidgets
  - ipython
  - fastf1
